# Generated by Django 5.1 on 2024-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='job_role',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
