# Generated by Django 5.1 on 2024-09-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_remove_student_phone_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='target_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
